### ISSUE TITLE
How to use CUDA

### ISSUE THREAD

**Issue by YangSangWan** [FourierMourier/yolov8-onnx-cpp#1]
I want use cuda.  help me...

★ My environment
- CUDA 11.8
- onnxruntime-gpu 1.15.1

but /nn/onnx_model_base.cpp   line 46

sessionOptions.AppendExecutionProvider_CUDA(cudaOption);     shutdown program... not exist log... 😪

**Comment by FourierMourier** [comment]
Hi! I haven't added some additional code for GPU usage yet but I'll do it sometime later, so don't worry
also using cuda requires having another package with "gpu" part in its name: 
[onnxruntime-win-x64-gpu-1.16.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.16.1/onnxruntime-win-x64-gpu-1.16.1.zip)

**Comment by YangSangWan** [comment]
oh i solved this problem!

1. in this page "https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html"
   check out "Requirements"
   my Environment CUDA 11.8   ->onnxruntime 1.15

2. download onnxruntime!  this page "https://github.com/microsoft/onnxruntime/releases"
    onnxruntime-win-x64-gpu-1.15.0.zip


   thank you

**Comment by FourierMourier** [comment]
I'm glad it helped
