### ISSUE TITLE
OpenCV Version

### ISSUE THREAD

**Issue by mjlee111** [FourierMourier/yolov8-onnx-cpp#10]
Does ONNX supports opencv 4.5.4? Tested on Ubuntu 22.04 and can't detect any objects.

**Comment by FourierMourier** [comment]
Hello there! Sorry for the late response. I specified the opencv version in the readme and that tells 4.80+ and I haven't tested the lower versions. So I guess it doesn't :)
upd.: typo

**Comment by mjlee111** [comment]
> Hello there! Sorry for the late response. I specified the opencv version in the readme and that tells 4.80+ and I haven't tested the lower versions. So I guess it doesn't :)
> 
> upd.: typo

Thanks for the reply. I've tested out lower versions of the OpenCV(4.5.2, 4.2.0, etc). Found out onnx doesn't works on any lower versions. 
Thank you  ◡̎.

**Comment by FourierMourier** [comment]
Btw, have you tried 4.80+ versions (at least I can confirm it works)? Using cmake was kind of smooth build process for me in any ide

**Comment by mjlee111** [comment]
> Btw, have you tried 4.80+ versions (at least I can confirm it works)? Using cmake was kind of smooth build process for me in any ide

Sure! It works fine with 4.80+ versions. I was working out with ROS2 yolo(ultralytics) onnx implementation. Which found out ROS2 environment does not smoothly adapts with other compiled OpenCV(in my case). Trying to figure out other way to solve this problem with my team. Really appreciate to your kindness. 😄

**Comment by FourierMourier** [comment]
Oh, i see where it comes from now ;) . As I've learned from deploying something on edge devices - the best way to do is to actually containerize the application (either via api/shared memory, depending on the specific case). I'd make sure that the code was compiled for the specific platform (i mean differences between arm/x86). Maybe this one will help. So just make this ml app standalone and call from the main application an ml one to remove the "dependency hell".
To be honest, I rarely managed to make ML solutions work together within a monolith with lots of libs
