### ISSUE TITLE
Pose onnx model

### ISSUE THREAD

**Issue by athanase** [FourierMourier/yolov8-onnx-cpp#2]
Awesome project.

Could it be possible for you to upload your yolov8n-pose.onnx ?

**Comment by FourierMourier** [comment]
@athanase Hi, sorry for the late response. I'm not sure whether it's still on my pc but you can actually use yolov8 repo and their docs to export the onnx model:
https://docs.ultralytics.com/modes/export/#arguments

You could pass any imgsz value (not just the one I used) - cpp backend will extract info from metadata automatically
