### ISSUE TITLE
Just saying thank you! 

### ISSUE THREAD

**Issue by K4HVH** [FourierMourier/yolov8-onnx-cpp#8]
Hey mate.

I just want to make it known to you that I used a lot of your code in my project [YOLOv8-ONNXRuntime-CPP](https://github.com/K4HVH/YoloV8-ONNXRuntime-CPP) 

I just want to say thank you for having your code publically available and of such a great quality. I've been struggling with performing inferencing for a while so this was a massive help.
I have credited you in both the Markdown and the Code itself aswell. 

(Sorry that this isn;t an actual issue to haha)

**Comment by FourierMourier** [comment]
Thank you so much for your kind words (and sorry for the delay)! I'm really glad to hear that it was useful ( and of high quality :) ). I'm still totally ok that it wasn't an actual issue btw
